echo Add1 && huffc src/Add1.huff -r | wc
echo BasicBank && huffc src/BasicBank.huff -r | wc
echo CallValue && huffc src/CallValue.huff -r | wc
echo CalldataLength && huffc src/CalldataLength.huff -r | wc
echo Create && huffc src/Create.huff -r | wc
echo Distributor && huffc src/Distributor.huff -r | wc
echo Donations && huffc src/Donations.huff -r | wc
echo Emitter && huffc src/Emitter.huff -r | wc
echo FooBar && huffc src/FooBar.huff -r | wc
echo Keccak && huffc src/Keccak.huff -r | wc
echo MaxOfArray && huffc src/MaxOfArray.huff -r | wc
echo Multiply && huffc src/Multiply.huff -r | wc
echo MyEtherBalance && huffc src/MyEtherBalance.huff -r | wc
echo NonPayable && huffc src/NonPayable.huff -r | wc
echo Return1 && huffc src/Return1.huff -r | wc
echo RevertCustom && huffc src/RevertCustom.huff -r | wc
echo RevertString && huffc src/RevertString.huff -r | wc
echo SendEther && huffc src/SendEther.huff -r | wc
echo SimpleStore && huffc src/SimpleStore.huff -r | wc
echo SimulateArray && huffc src/SimulateArray.huff -r | wc
echo SumArray && huffc src/SumArray.huff -r | wc
